FROM python:3.13.1-alpine3.21

COPY requirements.txt ./
RUN mkdir -p /app
RUN chmod -R 777 /app
COPY ./micro_app/ /app/

RUN apk update && apk add bash
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p workspace
RUN chmod -R 777 workspace
WORKDIR ~/workspace