# This workflow will install Python dependencies, run tests
name: Pytest

on: [workflow_call]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test main app with pytest
      run: |
        cd main_app
        python3 -m pytest
    - name: Test micro app with pytest
      run: |
        cd micro_app
        python3 -m pytest