name: Run github workflow
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    permissions:
      contents: read
    uses: ./.github/workflows/pylint.yml
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/python-test.yml
  push:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/push.yml