name: Run tests with allure on push
on: [workflow_call]


jobs:
  create-docker-build:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/pytest.yml
    with:
      tag_name: test-docker-image
      dockerfile: Dockerfile
      allure_result_folder: allure-results
    secrets: inherit