name: Run tests with allure on push
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    permissions:
      contents: read
    uses: ./.github/workflows/pylint.yml
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/python-test.yml