name: Run tests with allure on push
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  create-docker-build:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/pytest.yml
    with:
      tag_name: test-component-docker-image
      dockerfile: Dockerfile
      allure_result_folder: allure-results
    secrets: inherit